### ISSUE TITLE
uncaughtException Can't set headers after they are sent.

### ISSUE THREAD

**Issue by brandonlai** [krakenjs/adaro#34]
Is there a way to improve the stack trace in adaro?  I am not able to determine what causing my issue?  This only occurs once deployed and not locally.

Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:691:11)
    at ServerResponse.res.setHeader (/var/lib/openshift/53f40f114382ec37cc0005e8/app-root/runtime/repo/node_modules/connect-mongodb/node_modules/connect/lib/patch.js:62:20)
    at ServerResponse.header (/var/lib/openshift/53f40f114382ec37cc0005e8/app-root/runtime/repo/node_modules/express/lib/response.js:717:10)
    at ServerResponse.send (/var/lib/openshift/53f40f114382ec37cc0005e8/app-root/runtime/repo/node_modules/express/lib/response.js:146:12)
    at fn (/var/lib/openshift/53f40f114382ec37cc0005e8/app-root/runtime/repo/node_modules/express/lib/response.js:951:10)
    at Stub.callback (/var/lib/openshift/53f40f114382ec37cc0005e8/app-root/runtime/repo/node_modules/adaro/lib/engine.js:126:22)
    at Stub.flush (/var/lib/openshift/53f40f114382ec37cc0005e8/app-root/runtime/repo/node_modules/dustjs-linkedin/lib/dust.js:457:10)
    at Chunk.end (/var/lib/openshift/53f40f114382ec37cc0005e8/app-root/runtime/repo/node_modules/dustjs-linkedin/lib/dust.js:567:15)
    at /var/lib/openshift/53f40f114382ec37cc0005e8/app-root/runtime/repo/node_modules/adaro/lib/patch/index.js:85:53
    at /var/lib/openshift/53f40f114382ec37cc0005e8/app-root/runtime/repo/node_modules/adaro/lib/reader/js.js:39:13

**Comment by jasisk** [comment]
Try starting your app in prod mode:
`NODE_ENV=prod node .`

Are you able to reproduce the issue locally? If so, try:
`grunt build && NODE_ENV=prod node .`

Does that fix it?

**Comment by brandonlai** [comment]
Good tips.  I will remember for next time.  I believe these issues were due to some environmental issues with the openshift database.  Everything works now after a restarting all the services.

**Comment by lmarkus** [comment]
You might still want to go back to your code and check to see where you might be executing a callback twice. From the sounds of it, you may be using this bad pattern somewhere:

```javascript
    function doStuff(callback){
        callService(function (err, result){
            if(err){callback();}
            callback();
        })
    }
```
if there is an `err`, the callback function will be invoked twice (Which could cause something like what you were seeing, if say, res.render is called twice.)

The correct way would be:
`if(err){return callback()};`

**Comment by jasisk** [comment]
> You might still want to go back to your code and check to see where you might be executing a callback twice.

I recommended building assets because we commonly see this with folks who have built a project from the generator.

The generator—by default—configures the the kraken-owned [404](https://github.com/krakenjs/kraken-js/blob/9d04b7a6473737f6faf62abef2f4919843a99ef3/middleware/404.js) and [500](https://github.com/krakenjs/kraken-js/blob/9d04b7a6473737f6faf62abef2f4919843a99ef3/middleware/500.js) middlewares. Typically, what happens is something like this:

``` js
router.get('/route', function (req, res) {
    res.render('template', myModel);
});
```

The call to `res.render` fails and subsequently throws because `adaro` cannot find a template. `express` catches the throw, and bounces over to the error handling middleware. The error handling middleware then attempts to render again after having already set the response headers in the first call to render, thus :boom:.

So it's certainly possible @brandonlai isn't doubling up on the callback. Not sure if this is a case—specifically—where we can capture the error more elegantly. Regardless, `adaro` has been plagued with cryptic error messages, in part due to `dust`. @aredridel is diligently working on resolving a lot of those issues (aside: she deserves buckets of respect for diving-in to this stuff; it's not the most developer-friendly).

**Comment by aredridel** [comment]
Yeah. One thing that may help is replacing any instances of `spud@0.0.3` with `spud@1.1.1`. That fixes a lot of error path stuff.
